name: Go PR Checks

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Run tests
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
